server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        prefer-agent-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
#        - id: pay_routh1                # 路由ID, 要求唯一
#          uri: http://localhost:8001 # 匹配后提供服务的地址
#          predicates:
#            - Path=/pay/gateway/get/**    # 断言, 路径匹配后进行路由
#        - id: pay_routh12               # 路由ID, 要求唯一
#          uri: http://localhost:8001 # 匹配后提供服务的地址
#          predicates:
#            - Path=/pay/gateway/info/**    # 断言, 路径匹配后进行路由
        - id: pay_routh1                # 路由ID, 要求唯一
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/pay/gateway/get/**    # 断言, 路径匹配后进行路由
            - After=2024-04-03T16:12:00.000+08:00[Asia/Shanghai]
        - id: pay_routh12               # 路由ID, 要求唯一
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/pay/gateway/info/**    # 断言, 路径匹配后进行路由


